# Generated by Django 3.2 on 2021-05-12 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20210511_1556'),
    ]

    operations = [
        migrations.CreateModel(
            name='Commentaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Contenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=20)),
                ('texte', models.TextField(max_length=1000)),
                ('image', models.ImageField(upload_to='blog/images/')),
                ('position', models.IntegerField()),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.article')),
            ],
            options={
                'verbose_name': 'contenu',
            },
        ),
        migrations.CreateModel(
            name='TypeContenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'type',
            },
        ),
        migrations.RemoveField(
            model_name='image',
            name='article',
        ),
        migrations.RemoveField(
            model_name='liste',
            name='article',
        ),
        migrations.RemoveField(
            model_name='paragraphe',
            name='article',
        ),
        migrations.RemoveField(
            model_name='soustitre',
            name='article',
        ),
        migrations.DeleteModel(
            name='Citation',
        ),
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.DeleteModel(
            name='Liste',
        ),
        migrations.DeleteModel(
            name='Paragraphe',
        ),
        migrations.DeleteModel(
            name='SousTitre',
        ),
        migrations.AddField(
            model_name='contenu',
            name='typecontenu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.typecontenu'),
        ),
    ]
