# Generated by Django 3.2 on 2021-05-12 16:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210512_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='date_maj',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='date de mise à jour'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='article',
            name='date_public',
            field=models.DateField(blank=True, default=django.utils.timezone.now, verbose_name='date de publication'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='article',
            name='auteur',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='article',
            name='slug',
            field=models.SlugField(blank=True),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='image',
            field=models.ImageField(blank=True, upload_to='blog/images/'),
        ),
        migrations.AlterField(
            model_name='contenu',
            name='texte',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
