# Generated by Django 3.2 on 2021-05-26 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210512_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contenu',
            options={},
        ),
    ]
